@startuml

class Botella{
    - color: String
    - capacidadMáximaLitros: double
    - capacidadActualLitros: double
    - material: String
    - pesoOnzas: double
    - tapado: boolean

    + llenar()
    + llenar(otraBotella: Botella)
    + llenar(cantidadALlenar: double)

    - obtenerCapacidadResidual(): double
    - estaTapado(): boolean

    + vaciar()
    + vaciar(cantidadAVaciar: double)

    + tapar()
    + destapar()

    + imprimirCapacidadActual()

}

@enduml